### PR TITLE
Use `dist/index.js` as the package's entry point

### PR DESCRIPTION
**Pull request by adi-pjackson**
Potential fix for #177

### CODE REVIEW

**Comment by hckhanh** [comment]
I get this bug when I try to upgrade to v4 as well. Hope this bug will be fixed soon.

**Comment by adi-pjackson** [comment]
The appveyor failure looks like a permission issue, so hopefully a false positive 🤞

**Comment by michael-ciniawsky** [comment]
Closes #179  #177 

@adi-pjackson Thx

cc @jhnns Sry for making stress here 😛 but this one is important and should be temporarily fix the issue

**Comment by jhnns** [comment]
Damn it! 😁 Thx for the PR 👍 

@michael-ciniawsky Is this a bug in webpack-defaults? Or should we use ES2015 modules everywhere?

**Comment by michael-ciniawsky** [comment]
@jhnns Yep, seems it works with `0.4.4` now, ES2015 Modules weren't transpiled to CJS and the `src/cjs.js` wrapper wasn't added automatically, but changed in `package.json` 😛 

I tried updating to `import/export` all over the code base, but resolver related tests failed and we should in general test the transpiled code in `dist` to be sure there are no bugs in the build step, which likely needs changes to ´webpack-defaults` again, better keep it as is for the moment :D

**Comment by jhnns** [comment]
> I tried updating to import/export all over the code base, but resolver related tests failed and we should in general test the transpiled code in dist to be sure there are no bugs in the build step,

Yes. To be honest, I'm not very confident to build something and immediately release it without testing it. I'm paranoid in this regard ^^

> Maybe even just stick to require()/module.exports would be the saner path in general :)

Yes, I think so. Makes some things easier and CommonJS is just fine for Node.js.

**Comment by michael-ciniawsky** [comment]
> Yes. To be honest, I'm not very comfortable to build something and immediately release it without testing it. I'm paranoid in this regard ^^

Yep, not a bad habit when it comes to code 😛 . Should I nevertheless send PR (can be closed) or better omit unnessecary noise and you take a look later own your own?

**Comment by jhnns** [comment]
> Should I nevertheless send PR (can be closed) or better omit unnessecary noise and you take a look later own your own?

What do you mean? ^^ The issue is fixed now...

**Comment by michael-ciniawsky** [comment]
Temporarily fixed 😉 You can not use `webpack-defaults` if the `cjs.js` wrapper isn't added or it is removed from `wepack-defaults` in the future

**Pull request merged**
