### PR TITLE
fix: resolve `@import` with absolute paths

### PR DESCRIPTION
**Pull request by n1ru4l**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
fixes #93

**Comment by michael-ciniawsky** [comment]
@n1ru4l Please add a test for this

**Comment by n1ru4l** [comment]
@bebraw Since the class is encapsulated inside a function this seems pretty hard to test for me :/. Any suggestions how I should proceed?
@bebraw I think this can be achieved by `loaderUtils.urlToRequest(url, '')`

**Comment by bebraw** [comment]
@n1ru4l Yeah, I think it would take some refactoring (extracting class?) to test this. But it's worth doing to avoid breaking the feature in the future.

**Comment by n1ru4l** [comment]
@bebraw I will try that!

**Comment by n1ru4l** [comment]
@bebraw I added a test that does not require any refactoring

**Pull request merged**
