### PR TITLE
fix: webpack watching does not recover after broken less is fixed

### PR DESCRIPTION
**Pull request by sliwey**
fix: #278

### CODE REVIEW

**Comment by olegstepura** [comment]
Cool! Will there be a new release with this fix?

**Comment by olegstepura** [comment]
I'm sorry to ask this again, but is there any chance to have a new version released? @evilebottnawi @michael-ciniawsky
Thanks a lot!

**Comment by evilebottnawi** [comment]
@olegstepura yep, it was released in near future we want fix some other errors before release, sorry for delay

**Comment by olegstepura** [comment]
Sorry to ask, but why not release some intermediate minor version with a fix? E.g. `4.1.1`. A fix was merged a month ago but sadly there was still no release after that.

**Comment by sliwey** [comment]
I think @olegstepura is right. Maybe it can update a patch release? Because the current version has a little impact on development efficiency.

**Comment by evilebottnawi** [comment]
Done in `5.0.0

**Comment by olegstepura** [comment]
Thanks guys. I can confirm that the original issue is fixed in `5.0.0` release.

**Pull request merged**
