### PR TITLE
chore: add node 18 and update snapshot

### PR DESCRIPTION
**Pull request by harish-sethuraman**
### Motivation / Use-Case

Added node 18 test runner

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
Can someone re trigger test?

**Comment by alexander-akait** [comment]
I think something wrong with network on CI machines, maybe sense to comment test or rewrite it on mocks

**Comment by harish-sethuraman** [comment]
Do we have a PR of where we have done the same @alexander-akait  ?

**Comment by alexander-akait** [comment]
There is no PR, you need to write this code

**Comment by alexander-akait** [comment]
I will fix tests in another PR

**Pull request merged**
