### PR TITLE
docs(readme): remove deprecated  instructions

### PR DESCRIPTION
**Pull request by Wzb3422**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Since `~` is deprecated and all can be avoided safely. This PR removed all instructions about using deprecated `~` to avoid confusion.

### Breaking Changes

None

### Additional Info

See #459

### CODE REVIEW

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by Wzb3422** [comment]
> Can you accept CLA?

I used a wrong user email to commit, I corrected it. CLA is covered now.

**Comment by alexander-akait** [comment]
Looks like we need update snapshots, can you do it?

**Comment by alexander-akait** [comment]
Sorry for delay, thank you

**Pull request merged**
