### PR TITLE
fix: `NormalModuleReplacementPlugin` has no effect

### LINKED ISSUE #184: NormalModuleReplacementPlugin has no effect with less-loader@4
there is 3 files, a.less b.less c.less
 a import b, and i use NormalModuleReplacementPlugin to replace b to c

when i use webpack@1 and less-loader@2, b is replaced by c.

but, upgrade to webpack@2 and less-loader@4, nothing happend

### PR DESCRIPTION
**Pull request by snadn**
fixed #184

### CODE REVIEW

**Comment by snadn** [comment]
@jhnns @michael-ciniawsky this pr can be merged?

**Comment by michael-ciniawsky** [comment]
What's the use case for this ?

**Comment by snadn** [comment]
@michael-ciniawsky I use https://github.com/ant-design/ant-design in my  project and want to use my own config instead of `components/style/themes/default.less` in antd.

my webpack config is 
image

**Comment by jhnns** [comment]
Thanks for your PR @snadn 👍 

Have you tried using the `resolve.alias` option? We have [a test for that use case](https://github.com/webpack-contrib/less-loader/blob/a3f9601c9439471f7f0ce9b4a59ba4cf9e178c43/test/index.test.js#L79). If yes, why didn't it work for you?

**Comment by snadn** [comment]
I need replace some file in `antd` and components in `antd` import the file use relative path

**Comment by snadn** [comment]
I dont think this pr is for specific libraries, I just want it work with 'NormalModuleReplacementPlugin'.

and then it will be the best way for my situation.

**Comment by JounQin** [comment]
@michael-ciniawsky So what do you think why webpack provides such a plugin? We should be able to completely control our dependencies and modules. Or at least an option for user is needed.

**Pull request closed without merging**
