### PR TITLE
change context by using paths array

### PR DESCRIPTION
**Pull request by donaldpipowitch**
Less supports to additional contexts by using a paths array as an option (see http://lesscss.org/usage/#command-line-usage-options). This is only done, if the default context can't be resolved.

> If the file in an @import rule does not exist at that exact location, less will look for it at the location(s) passed to this option. You might use this for instance to specify a path to a library which you want to be referenced simply and relatively in the less files.

It can be used like this:

```
{
  test: /\.less$/,
  loader: `less?sourceMap&paths[]=${additionalDirectoryPath}`
}
```

This is a crucial feature to easily integrate webpack into existing projects.

### CODE REVIEW

**Comment by Craga89** [comment]
When using this patch in Windows, I'm getting failures to resolve the paths inside `tryResolvingPath` due to what looks like a wrong `context` being passed through for `@import` statements that reside in any files that are resolved via a `paths` config. For example:

My file structure is as follows

```
less
  - base.less
node_modules
  - cc-css
    - less
      - base.less
      - layout.less
```

```less
# File: less\base.less
@import 'cc-css/less/base'
```

```less
# File: node_modules\cc-css\less\base.less
@import 'layout';
```

Gives an error:

```
ERROR in ./~/css-loader?sourceMap!./~/less-loader?{"sourceMap":true,"paths":["e:/git/cc-designer/node_modules"]}!./less/base.less
Module build failed: Cannot resolve module 'layout.less' in e:/git/cc-designer/node_modules
 @ e:/git/cc-designer\node_modules\cc-css\less\base.less (line 1, column 0)
 near lines:
   @import 'layout';

 @ ./less/base.less 4:14-194 13:2-17:4 14:20-200
```

Debugging the code reveals that one Windows, the `currentDirectory` trying to be resolved is actually `e:\git`, not the correct `/e/Git/cc-designer/node_modules/cc-css/less/` that I'd expect

```
filename: reference.less
currentDirectory: e:/git/
context: e:/git/cc-designer/node_modules

**Comment by gjuchault** [comment]
What is the status of this issue ?

**Comment by mediafreakch** [comment]
less-loader uses a custom implementation as the file-manager for less. Honestly I don't understand why, can't it just cut all of that and simply provide less with the paths to search for via webpack.config (like in the pull request above)?

**Comment by admosity** [comment]
Any reason in particular this hasn't been merged yet? I'm not quite following the issue here.

**Comment by cvharris** [comment]
how come this hasn't been merged yet?

**Comment by jhnns** [comment]
This has also been discussed [at the sass-loader](https://github.com/webpack-contrib/sass-loader/pull/307) and I totally understand the motivation.

I'm thinking about making the webpack resolution plugin opt-in. It's the source for many errors and often it also makes the build considerably slower (at least Sass, I haven't tested it with Less).

**Comment by jhnns** [comment]
Starting with less-loader 4, you can now choose between the builtin Less resolver or the webpack resolver. If you specify a `paths` option, it will not use the webpack resolver at all. [Take a look at the README for further information](https://github.com/webpack-contrib/less-loader#imports).

It decided to do it that way because specifying the `paths` option *and* using the webpack resolver doesn't really make sense to me. If you use the webpack resolver, you can have the same behavior as the `paths` option by adding an absolute path to [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules).

Thx @donaldpipowitch for your efforts. I hope, this change is in your interest.

**Pull request closed without merging**
